jobs:
  Litemall-admin:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      run: npm --prefix litemall-admin install
    - continue-on-error: true
      run: npm --prefix litemall-admin run test
    strategy:
      matrix:
        node-version:
        - 10.x
        - 12.x
        - 14.x
  Litemall-all:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    strategy:
      matrix:
        java-version:
        - 8
        - 8.0.192
        - 11
        - 11.0.3
  Litemall-vue:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      run: npm --prefix litemall-vue install
    - continue-on-error: true
      run: npm --prefix litemall-vue run test
    strategy:
      matrix:
        node-version:
        - 10.x
        - 12.x
        - 14.x
name: Actions
on:
  repository_dispatch:
    types: trigger-ga___main.yml
